from colorama import Fore,Style
plaka_numaralari={
"01" : "Adana",
"02" : "Adıyaman",
"03" : "Afyonkarahisar",
"04" : "Ağrı",
"05" : "Amasya",
"06" : "Ankara",
"07" : "Antalya",
"08" : "Artvin",
"09" : "Aydın",
"10" : "Balıkesir",
"11" : "Bilecik",
"12" : "Bingöl",
"13" : "Bitlis",
"14" : "Bolu",
"15" : "Burdur",
"16" : "Bursa",
"17" : "Çanakkale",
"18" : "Çankırı",
"19" : "Çorum",
"20" : "Denizli",
"21" : "Diyarbakır",
"22" : "Edirne",
"23" : "Elâzığ",
"24" : "Erzincan",
"25" : "Erzurum",
"26" : "Eskişehir",
"27" : "Gaziantep",
"28" : "Giresun",
"29" : "Gümüşhane",
"30" : "Hakkâri",
"31" : "Hatay",
"32" : "Isparta",
"33" : "Mersin",
"34" : "İstanbul",
"35" : "İzmir",
"36" : "Kars",
"37" : "Kastamonu",
"38" : "Kayseri",
"39" : "Kırklareli",
"40" : "Kırşehir",
"41" : "Kocaeli",
"42" : "Konya",
"43" : "Kütahya",
"44" : "Malatya",
"45" : "Manisa",
"46" : "Kahramanmaraş",
"47" : "Mardin",
"48" : "Muğla",
"49" : "Muş",
"50" : "Nevşehir",
"51" : "Niğde",
"52" : "Ordu",
"53" : "Rize",
"54" : "Sakarya",
"55" : "Samsun",
"56" : "Siirt",
"57" : "Sinop",
"58" : "Sivas",
"59" : "Tekirdağ",
"60" : "Tokat",
"61" : "Trabzon",
"62" : "Tunceli",
"63" : "Şanlıurfa",
"64" : "Uşak",
"65" : "Van",
"66" : "Yozgat",
"67" : "Zonguldak",
"68" : "Aksaray",
"69" : "Bayburt",
"70" : "Karaman",
"71" : "Kırıkkale",
"72" : "Batman",
"73" : "Şırnak",
"74" : "Bartın",
"75" : "Ardahan",
"76" : "Iğdır",
"77" : "Yalova",
"78" : "Karabük",
"79" : "Kilis",
"80" : "Osmaniye",
"81" : "Düzce"
}

ters_plaka_numaralari = {
'Adana': '01', 
'Adıyaman': '02', 
'Afyonkarahisar': '03', 
'Ağrı': '04', 
'Amasya': '05', 
'Ankara': '06', 
'Antalya': '07', 
'Artvin': '08', 
'Aydın': '09', 
'Balıkesir': '10', 
'Bilecik': '11', 
'Bingöl': '12', 
'Bitlis': '13', 
'Bolu': '14', 
'Burdur': '15', 
'Bursa': '16', 
'Çanakkale': '17', 
'Çankırı': '18', 
'Çorum': '19', 
'Denizli': '20', 
'Diyarbakır': '21', 
'Edirne': '22', 
'Elâzığ': '23', 
'Erzincan': '24', 
'Erzurum': '25', 
'Eskişehir': '26', 
'Gaziantep': '27', 
'Giresun': '28', 
'Gümüşhane': '29', 
'Hakkâri': '30', 
'Hatay': '31', 
'Isparta': '32', 
'Mersin': '33', 
'İstanbul': '34', 
'İzmir': '35', 
'Kars': '36', 
'Kastamonu': '37', 
'Kayseri': '38', 
'Kırklareli': '39', 
'Kırşehir': '40', 
'Kocaeli': '41', 
'Konya': '42', 
'Kütahya': '43', 
'Malatya': '44', 
'Manisa': '45', 
'Kahramanmaraş': '46', 
'Mardin': '47', 
'Muğla': '48', 
'Muş': '49', 
'Nevşehir': '50', 
'Niğde': '51', 
'Ordu': '52', 
'Rize': '53', 
'Sakarya': '54', 
'Samsun': '55', 
'Siirt': '56', 
'Sinop': '57', 
'Sivas': '58', 
'Tekirdağ': '59', 
'Tokat': '60', 
'Trabzon': '61', 
'Tunceli': '62', 
'Şanlıurfa': '63', 
'Uşak': '64', 
'Van': '65', 
'Yozgat': '66', 
'Zonguldak': '67', 
'Aksaray': '68', 
'Bayburt': '69', 
'Karaman': '70', 
'Kırıkkale': '71', 
'Batman': '72', 
'Şırnak': '73', 
'Bartın': '74', 
'Ardahan': '75', 
'Iğdır': '76', 
'Yalova': '77', 
'Karabük': '78', 
'Kilis': '79', 
'Osmaniye': '80', 
'Düzce': '81'}

kullanici_secimi = input(Style.BRIGHT + Fore.GREEN + "Şehir mi, Plaka mı sorgulayacaksın? Şehir için 1, Plaka için 2 yaz\n")

if kullanici_secimi=="1":
    kullanici_degeri=input(Style.BRIGHT + Fore.GREEN + "Hangi şehrin plaka kodunu arıyorsunuz?\n")
    sadece_tek_buyuk_harf = kullanici_degeri.capitalize()
    print(ters_plaka_numaralari.get(sadece_tek_buyuk_harf,Style.BRIGHT + Fore.RED + "YAZIM HATASI!"))
else:
    kullanici_degeri=input(Style.BRIGHT + Fore.GREEN + "Aranacak Plaka kodunu rakam ile yazın\n")
    if len(kullanici_degeri)<2:
        basina_sifir_eklenmis = "0"+kullanici_degeri
        print(plaka_numaralari.get(basina_sifir_eklenmis,Style.BRIGHT + Fore.RED + "YAZIM HATASI!"))
    else:
        print(plaka_numaralari.get(kullanici_degeri,Style.BRIGHT + Fore.RED + "YAZIM HATASI!"))
